/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WikieWebsiteRouteImport } from './routes/wikie-website'

const WikieWebsiteRoute = WikieWebsiteRouteImport.update({
  id: '/wikie-website',
  path: '/wikie-website',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/wikie-website': typeof WikieWebsiteRoute
}
export interface FileRoutesByTo {
  '/wikie-website': typeof WikieWebsiteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/wikie-website': typeof WikieWebsiteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/wikie-website'
  fileRoutesByTo: FileRoutesByTo
  to: '/wikie-website'
  id: '__root__' | '/wikie-website'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  WikieWebsiteRoute: typeof WikieWebsiteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wikie-website': {
      id: '/wikie-website'
      path: '/wikie-website'
      fullPath: '/wikie-website'
      preLoaderRoute: typeof WikieWebsiteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  WikieWebsiteRoute: WikieWebsiteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
